config/routes.rb
ProjectLearningApp::Application.routes.draw do
  resources :locations
  
  resources :articles
  get 'tags/:tag', to: 'articles#index', as: :tag


  get "password_resets/new"

  get "sessions/new"

  resources :projects do
    resources :stories
  end

  resources :stories

  resources :stories do
    resources :tasks
  end
  
  resources :tasks

  
  get 'sign_up', to: 'users#new', :as => 'sign_up'
  #  root :to => "users#new"
  resources :users
  resources :user_steps
  
  get 'log_in', to: 'sessions#new', :as => 'log_in'
  get 'log_out', to: 'sessions#destroy', :as => 'log_out'
  resources :sessions
  
  resources :password_resets

  resources :messages
  
  resources :surveys
  
  #resources :products
  
  resources :categories
  
  resources :products do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end

	root to: 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :name, :content, :tag_list
  acts_as_taggable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  respond_to :html

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      redirect_to articles_url
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: 'Article successfully changed'
    else
      render action: 'edit'   
    end
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :name %>
  <%= f.input :tag_list, label: 'Tags separated by comas' %>
  <%= f.input :content, input_html: {rows: 8} %>
  
  <%= f.button :submit %>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div id="tag_cloud">
  <% tag_cloud Article.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class%>
  <% end %>
</div>

<% @articles.each do |article| %>
  <h2><%= link_to article.name, article_path(article.id) %></h2>
  <%= article.content %>
  <p>Tags: <%= raw article.tag_list.map {|tag| link_to tag, tag_path(tag)}.join(', ') %></p>
  </br>
<% end %>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h2>New Article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2><%= @article.name%></h2>
</br>
<%= @article.content %>
</br>
<%= link_to 'Edit Article', edit_article_path(@article.id) %>
<%= link_to 'Back', articles_path %>