config/routes.rb
ProjectLearningApp::Application.routes.draw do
  resources :locations
  
  resources :articles
  get 'tags/:tag', to: 'articles#index', as: :tag


  get "password_resets/new"

  get "sessions/new"

  resources :projects do
    resources :stories
  end

  resources :stories

  resources :stories do
    resources :tasks
  end
  
  resources :tasks

  
  get 'sign_up', to: 'users#new', :as => 'sign_up'
  #  root :to => "users#new"
  resources :users
  resources :user_steps
  
  get 'log_in', to: 'sessions#new', :as => 'log_in'
  get 'log_out', to: 'sessions#destroy', :as => 'log_out'
  resources :sessions
  
  resources :password_resets

  resources :messages
  
  resources :surveys
  
  #resources :products
  
  resources :categories
  
  resources :products do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end

	root to: 'home#index'

end

app/views/shared/_navigation.html.erb
<div class='navbar navbar-inverse navbar-fixed-top'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='btn btn-navbar' data-target='.nav-collapse' data-toggle='collapse'> <span class='icon-bar'></span> <span class='icon-bar'></span> <span class='icon-bar'></span> </a>
      <a href="/" class="brand">Project Management Tool</a>
      <ul class='nav pull-right'>
        <li class='dropdown'>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class='icon-user icon-white'></i>
          <b class='caret'></b> </a>
          <ul class='dropdown-menu'>
            <li>
              <a href="#"><i class='icon-cog'></i> Settings </a>
            </li>
          </ul>
        </li>
      </ul>
      <div class='nav-collapse'>
        <ul class='nav'>
          <li>
            <%= link_to 'Projects', projects_path %>
          </li>
          <li>
            <%= link_to 'Messages', messages_path %>
          </li>
          <li>
            <%= link_to 'Users', users_path %>
          </li>
          <li>
            <%= link_to 'Surveys', surveys_path %>
          </li>
          <li>
            <%= link_to 'Locations', locations_path %>
          </li>
          <li>
            <%= link_to 'Articles', articles_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>