config/routes.rb
ProjectLearningApp::Application.routes.draw do
  resources :locations
  
  resources :articles
  get 'tags/:tag', to: 'articles#index', as: :tag


  get "password_resets/new"

  get "sessions/new"

  resources :projects do
    resources :stories
  end

  resources :stories

  resources :stories do
    resources :tasks
  end
  
  resources :tasks

  
  get 'sign_up', to: 'users#new', :as => 'sign_up'
  #  root :to => "users#new"
  resources :users
  resources :user_steps
  
  get 'log_in', to: 'sessions#new', :as => 'log_in'
  get 'log_out', to: 'sessions#destroy', :as => 'log_out'
  resources :sessions
  
  resources :password_resets

  resources :messages
  
  resources :surveys
  
  #resources :products
  
  resources :categories
  
  resources :products do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end

	root to: 'home#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, reject_if: ->(t) { t['content'].blank? }, allow_destroy: true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  skip_before_filter :require_login
  
  respond_to :html

  def index
    @surveys = Survey.all
  end
  
  def new
    @survey = Survey.new
    3.times do
      question = @survey.questions.build
      4.times { question.answers.build }
    end
  end
  
  def create
    @survey = Survey.new(params[:survey])
    
    if @survey.save
      redirect_to surveys_url
    else
      render :new
    end
  end 
  
  def show
    @survey=Survey.find(params[:id])
  end
end

app/views/surveys/_answer_fields.html.erb
<%= f.input :content, label: 'Answer', :input_html => { :rows => 3 }%>
<%= f.input :_destroy, label: 'Remove', as: :boolean %>

app/views/surveys/_form.html.erb
<%= simple_form_for @survey, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.simple_fields_for :questions do |q| %>
    <%= render 'question_fields', f: q %>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/surveys/_question_fields.html.erb
<%= f.input :content, label: 'Question', :input_html => { :rows => 3 }%>
<%= f.input :_destroy, label: 'Remove', as: :boolean %>

<%= f.simple_fields_for :answers do |a| %>
    <%= render 'answer_fields', f: a %>
  <% end %>

app/views/surveys/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <% if @surveys.any? %>
    <table class='table table-striped table-condensed'>
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @surveys.each do |survey| %>
        <tr>
          <td><%= link_to survey.name, survey %></td>
          <td></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <div class="alert alert-info">No surveys found.</div>
    <% end %>
    <div>
      <%= link_to 'New Survey', new_survey_path %>
    </div>
  </div>
</div>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

app/views/surveys/show.html.erb
<h1>Survey</h1>
<p>
  <strong>Name:</strong>
  <%=h @survey.name %>
</p>

<ol>
  <% for question in @survey.questions %>
  <li><%= h question.content %></li>
  <ul>
    <% for answer in question.answers %>
      <li><%= h answer.content %></li>
    <% end %>
  </ul>
  <% end %>
</ol>

<p>
  <%= link_to "Edit", edit_survey_path(@survey) %> |
  <%= link_to "Destroy", @survey, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", surveys_path %>
</p>